select CUSTOMER_ID, NAME, CATEGORY, PRODUCT, to_number(PRICE_INR_,38,2) as PRICE
from MYDB.CASE_STUDY_ONE_DRIVE.CUSTOMER_DATA_SHEET_1
union by name
select CUSTOMER_ID, NAME, CATEGORY, PRODUCT, PRICE
from MYDB.CASE_STUDY_POSTGRES_MYSCHEMA.CUSTOMER_PURCHASES